import { Article } from './supabase'

export const mockArticles: Article[] = [
  {
    id: '1',
    slug: 'how-to-rank-higher-on-etsy-search',
    title: 'How to Rank Higher on Etsy Search in 2024',
    excerpt: 'Learn the proven SEO strategies top Etsy sellers use to dominate search results and drive consistent traffic to their shops.',
    content: `# How to Rank Higher on Etsy Search in 2024\n\nEtsy search is the primary way buyers discover products. With over 90 million buyers, getting your listings in front of the right people can transform your shop from a hobby into a thriving business.\n\n## Understanding Etsy's Algorithm\n\nEtsy's search algorithm considers several key factors when ranking listings:\n\n**1. Relevancy** — How well your title, tags, and description match a buyer's search query.\n\n**2. Listing quality score** — Based on how often shoppers click and purchase your listing relative to how often it's shown.\n\n**3. Shop quality score** — Your overall shop performance, including reviews, sales history, and how complete your shop is.\n\n**4. Recency** — Newer listings get a temporary boost. Renewing listings can help, but focus on quality first.\n\n## Keyword Research That Works\n\nStart with the search bar. Type a partial phrase and see what Etsy auto-suggests — these are real searches buyers are making. Tools like Marmalead and eRank can give you search volume data.\n\nTarget **long-tail keywords** like "personalized oak wedding gift" instead of just "wedding gift." Less competition, more buyer intent.\n\n## Optimizing Your Titles\n\nPut your most important keywords in the first 40 characters — that's what appears in search results. Be descriptive but natural. Don't just stuff keywords.\n\nGood: "Personalized Oak Cutting Board — Wedding Gift for Couple, Custom Engraved"\nBad: "cutting board wood oak personalized custom wedding gift couple"\n\n## Using All 13 Tags\n\nEtsy gives you 13 tags — use all of them. Use multi-word phrases, not single words. Think like a buyer: what would they type?\n\n- "personalized wedding gift"\n- "custom cutting board"\n- "engraved kitchen gift"\n- "5th anniversary gift wood"\n\n## Attributes Matter\n\nFill in every attribute Etsy offers for your category. These feed directly into search filters buyers use.\n\n## Photography as a Conversion Tool\n\nYour thumbnail is your first impression. High click-through rate (CTR) signals to Etsy that buyers love your listing, boosting your rank. Invest in clean, bright photography with a clear main subject.\n\n## Getting Early Reviews\n\nReach out to your network for initial sales and honest reviews. A listing with 10+ reviews converts dramatically better than one with zero.\n\n## Track and Iterate\n\nUse Etsy Stats and tools like eRank to see which keywords bring traffic. Double down on what's working. Test new titles A/B style by changing one listing at a time.\n\nSEO on Etsy is a long game, but sellers who master it see compounding results month over month.`,
    category: 'Growth',
    author: 'Maya Chen',
    read_time: 7,
    published_at: '2024-01-15T10:00:00Z',
    featured: true,
    cover_image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80'
  },
  {
    id: '2',
    slug: 'pricing-your-handmade-products',
    title: 'The Real Formula for Pricing Your Handmade Products',
    excerpt: "Stop undercharging. Here's the exact pricing formula successful Etsy sellers use to stay profitable and grow sustainably.",
    content: `# The Real Formula for Pricing Your Handmade Products\n\nUnderpricing is the #1 mistake new Etsy sellers make. They set prices based on what they "think" buyers will pay instead of what makes business sense. Let's fix that.\n\n## The Full Cost Formula\n\n**Price = (Materials + Labor + Overhead) × 2 + Etsy Fees**\n\nLet's break that down:\n\n### Materials\nEvery supply that goes into the product. Include packaging! The box, tissue paper, ribbon, and thank-you card all cost money.\n\n### Labor\nPay yourself a real hourly wage. At minimum $15/hour. Track your time honestly — most makers underestimate this by 40%.\n\n### Overhead\nMonthly expenses ÷ number of items you make per month:\n- Etsy subscription\n- Tools and equipment (amortized)\n- Software subscriptions\n- Shipping supplies\n- Photography equipment\n\n### Etsy Fees\nEtsy charges:\n- 6.5% transaction fee\n- $0.20 listing fee per sale\n- ~3% + $0.25 payment processing\n\nSo roughly 10% of your sale price goes to fees. Factor this in.\n\n## The ×2 Markup\n\nThe doubling factor isn't greed — it's what allows you to wholesale, run sales, invest in advertising, and actually build a business. Without it, you're just covering costs.\n\n## Real Example\n\nHand-poured soy candle:\n- Materials: $4.50 (wax, wick, fragrance, jar, label, packaging)\n- Labor: 30 min at $15/hr = $7.50\n- Overhead allocation: $1.50\n- Subtotal: $13.50\n- ×2 = $27\n- Add 10% for fees: $29.70\n- **Round to $32**\n\nDoesn't $32 feel high? That's the undervaluing mindset at work. Look at top candle sellers on Etsy — most price at $28-40.\n\n## How to Raise Prices Without Losing Customers\n\n1. **Increase gradually** — 10-15% at a time\n2. **Improve packaging** to justify the premium\n3. **Add photography** that communicates value\n4. **Write better descriptions** that tell the story\n5. **Don't announce it** — just change the price\n\n## The Value Perception Game\n\nBuyers on Etsy are paying for uniqueness, story, and craftsmanship — not just a product. Price confidently, and high prices actually signal quality.\n\nIf nobody questions your prices, they're probably too low.`,
    category: 'Pricing',
    author: 'James Okafor',
    read_time: 6,
    published_at: '2024-01-22T10:00:00Z',
    featured: false,
    cover_image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80'
  },
  {
    id: '3',
    slug: 'product-photography-with-iphone',
    title: 'Stunning Product Photos with Just Your iPhone',
    excerpt: 'A professional camera is optional. Great light, composition, and these simple techniques will make your listings shine.',
    content: `# Stunning Product Photos with Just Your iPhone\n\nYour photos are your shop window. On Etsy, buyers can't touch or smell your products — the photo has to do all that work. Good news: your iPhone is more than capable.\n\n## Light is Everything\n\nNatural light from a window is your best friend. Here's the setup:\n\n1. Find a window with bright indirect light (not direct sunlight)\n2. Place your product 1-2 feet from the window\n3. Shoot between 10am-2pm for the best light\n4. Use a white foam board on the opposite side to bounce light and reduce shadows\n\nOvercast days are actually perfect — the clouds act as a giant diffuser.\n\n## Your Backdrop\n\nKeep it simple:\n- **White or light gray** for a clean, catalog look\n- **Natural textures** (linen, wood, marble) for a lifestyle feel\n- **Colored paper** from a craft store for seasonal shots\n\nConsistency matters more than perfection. Use the same backdrop style across your shop for a cohesive look.\n\n## Composition Rules\n\n**The Rule of Thirds** — Place your subject at the intersection of imaginary grid lines, not dead center.\n\n**Negative space** — Don't fill the frame. Give your product room to breathe. Empty space draws the eye.\n\n**Flat lay vs. 3D** — Flat lays work great for small items. 3D/angled shots show depth and scale.\n\n## iPhone Settings\n\n- **Portrait mode** for close-ups (creates that blurry background effect)\n- **Lock exposure** — tap and hold on your subject to lock focus and exposure\n- **Grid lines** — turn these on in Camera settings for easier composition\n- **Shoot in ProRAW** if your phone supports it — more editing flexibility\n\n## Editing (Free Apps)\n\n**Lightroom Mobile** (free) is the gold standard:\n1. Bump up Exposure slightly\n2. Increase Clarity to add crispness\n3. Adjust White Balance to make whites look truly white\n4. Add a tiny bit of Vibrance\n\nAvoid filters and heavy processing. Your photos should look real, not Instagram.\n\n## The 10-Shot Rule\n\nFor every listing, aim for these 10 shots:\n1. Clean product on white\n2. Product in use / lifestyle shot\n3. Close-up of texture or detail\n4. Scale reference (hand, coin, ruler)\n5. Multiple variants together\n6. Packaging shot\n7. Before/after (if applicable)\n8. Flat lay with complementary props\n9. Back/bottom/inside view\n10. Inspirational styled scene\n\nEtsy allows 10 photos per listing — use all of them.`,
    category: 'Photography',
    author: 'Priya Sharma',
    read_time: 8,
    published_at: '2024-02-03T10:00:00Z',
    featured: false,
    cover_image: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=1200&q=80'
  },
  {
    id: '4',
    slug: 'pinterest-marketing-for-etsy',
    title: 'How Pinterest Drives 60% of My Etsy Traffic',
    excerpt: "One seller's strategy for turning Pinterest into a consistent, free traffic machine for her Etsy shop.",
    content: `# How Pinterest Drives 60% of My Etsy Traffic\n\nI started taking Pinterest seriously 18 months ago. Today it drives more traffic to my Etsy shop than all other channels combined. Here's exactly what I do.\n\n## Why Pinterest Works for Etsy\n\nPinterest isn't a social media platform — it's a visual search engine. People use it to plan purchases, find inspiration, and save things they intend to buy. The intent is high. The competition for attention is lower than Instagram.\n\nAnd unlike Instagram, Pinterest content has a **long shelf life**. A pin I created 14 months ago still drives traffic every single week.\n\n## Setting Up Your Account\n\n1. **Convert to a Business account** (free) for analytics\n2. **Claim your website** and your Etsy shop\n3. **Enable Rich Pins** — these pull product info directly from your listings\n4. **Complete your profile** with keywords in your name and bio\n\n## Board Strategy\n\nCreate 8-12 boards organized around your customers' interests, not just your products:\n\n- "Handmade Kitchen Gifts" (where you'd pin your cutting boards)\n- "Cozy Home Decor Ideas" \n- "Gift Ideas for Mom"\n- "Small Business Tips" (re-pin helpful content)\n- "Our Workshop Behind the Scenes"\n\nNaming boards with search terms people actually use is critical.\n\n## Creating Pins That Convert\n\n**Vertical format** wins: 2:3 ratio (e.g., 1000×1500px)\n\n**Text overlay** is powerful: Add a short, bold title like "The Perfect Personalized Gift" to your image\n\n**Bright, warm images** perform better than dark, moody ones on Pinterest\n\n**Multiple pins per product**: Create 3-5 different pin designs for each product. Test different images and titles.\n\n## The Content Mix\n\n- 40% your own products\n- 30% lifestyle and inspiration content (re-pins)\n- 30% helpful tips and blog content\n\nPinterest rewards consistent pinners who share diverse content.\n\n## Keyword Optimization\n\nFor every pin:\n- Title: Include your main keyword naturally\n- Description: 150-300 words with 3-5 relevant keywords\n- Board: Make sure it's in a relevant keyword-named board\n- Hashtags: 2-5 specific hashtags\n\nFind keywords by typing in Pinterest's search bar and using the suggested bubbles.\n\n## Consistency Over Volume\n\nPin 10-15 times per day, but use a scheduler like Tailwind so you're not at your phone all day. Spread pins throughout the day. Consistent daily activity outperforms weekly posting bursts.\n\n## My Results\n\n- Month 1: 2,000 monthly views\n- Month 6: 45,000 monthly views  \n- Month 12: 180,000 monthly views\n- Month 18: 340,000 monthly views, 60% of Etsy traffic\n\nIt compounds. Start now.`,
    category: 'Marketing',
    author: 'Lauren Park',
    read_time: 9,
    published_at: '2024-02-14T10:00:00Z',
    featured: false,
    cover_image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=80'
  },
  {
    id: '5',
    slug: 'from-side-hustle-to-full-time',
    title: 'From Side Hustle to $8K/Month: My 3-Year Etsy Journey',
    excerpt: 'Sarah quit her office job after tripling her Etsy income. She shares the exact milestones, mistakes, and mindset shifts that made it possible.',
    content: `# From Side Hustle to $8K/Month: My 3-Year Etsy Journey\n\nThree years ago I was making $200/month on Etsy while working a 9-5 in marketing. Last month I made $8,400. Here's what actually happened.\n\n## Year One: Learning and Failing\n\nI opened my shop selling hand-lettered prints. I had beautiful products and terrible photos, inconsistent pricing, and no real understanding of SEO.\n\n**Revenue: $2,400 for the year**\n\nMistakes I made:\n- Priced too low (prints for $8 — I was making $2 profit after fees and supplies)\n- Had 12 listings and never added new ones\n- Ignored Etsy stats completely\n- Quit marketing after two weeks because "it wasn't working"\n\nThe turning point was joining a seller community and realizing I was doing almost everything wrong.\n\n## Year One Changes\n\nI spent three months studying before relisting:\n- Repriced everything using a real formula\n- Retook every photo with a ring light setup\n- Researched keywords obsessively\n- Set a goal of 100 listings in 90 days\n\n## Year Two: Finding My Groove\n\n**Revenue: $18,000**\n\nThe 100-listing push changed everything. More listings meant more entry points into search. My quality score improved as sales came in.\n\nKey moves:\n- Started a Pinterest account (slow build at first)\n- Added digital downloads as passive income\n- Began a simple email list through my Etsy confirmation messages\n- Raised prices 20% twice — didn't lose sales either time\n\nBy month 18, I was making $1,200/month consistently. That's when I started thinking seriously about going full-time.\n\n## The Math for Going Full-Time\n\nI needed to match my salary of $48,000/year, or $4,000/month. I gave myself a target: **six consecutive months at $3,500+** before I'd hand in notice.\n\nI hit it in month 22. I still waited.\n\n## Year Three: Scale and Systems\n\n**Revenue: $68,000**\n\nI quit my job in month 26. The freedom was terrifying and wonderful.\n\nWhat changed:\n- Hired a part-time production assistant (10 hrs/week at first)\n- Systematized everything with Notion and Trello\n- Launched a wholesale line for local boutiques\n- Started offering custom orders (3x the margin)\n- Built an email list to 4,200 subscribers\n\n## The Honest Part\n\nIt wasn't glamorous. There were months at $6,000 followed by months at $3,200. Holiday Q4 is now 35% of my annual revenue — the pressure is real.\n\nI work harder than I did at my office job. But I work on my own terms, make more money, and built something that's mine.\n\n## What I'd Tell Year-One Me\n\n1. Charge more. You're worth it.\n2. Treat it like a business from day one.\n3. Your photos matter more than anything else.\n4. Consistency beats intensity. Show up every week.\n5. Community is not optional. Find your people.\n\nThe Etsy opportunity is real. It's not passive income and it's not easy — but it is possible.`,
    category: 'Stories',
    author: 'Sarah Mitchell',
    read_time: 10,
    published_at: '2024-02-28T10:00:00Z',
    featured: false,
    cover_image: 'https://images.unsplash.com/photo-1556742044-3c52d6e88c62?w=1200&q=80'
  }
]
